# Config definitiva Domenico60
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Necessario perché nel PCB usiamo P0.10-LF come col14.
# Su nRF52840 P0.09/P0.10 possono essere pin NFC: così vengono usati come GPIO.
CONFIG_NFCT_PINS_AS_GPIOS=y
