# Test USB-only: Bluetooth disattivato temporaneamente.
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n
CONFIG_ZMK_SLEEP=n

# Necessario per usare P0.09/P0.10 come GPIO su nRF52840.
# P0.09 e P0.10 sono anche pin NFC, quindi senza questa riga possono non funzionare come GPIO.
CONFIG_NFCT_PINS_AS_GPIOS=y
